version: 2

sources:
  - name: jaffle_shop
    description: This a replica of the Postgres database used by our app
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: One record per customer
      - name: orders
        description: One record per order. Includes cancelled and deleted orders.
        
  - name: stripe
    description: This a replica of the Postgres database used by our app
    database: raw
    schema: stripe
    tables:
      - name: payment
        description: One record per order. Includes payment details.